name: "Notion backup"

on:
  workflow_dispatch:
  schedule:
    -   cron: "0 1 * * *"

jobs:
  backup:
    name: Backup
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'

      - uses: porohkun/notion-backup@v1
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_SPACE_ID: ${{ secrets.NOTION_SPACE_ID }}
      
      - uses: elstudio/actions-js-build/commit@v3
        with:
          commitMessage: Notion backup
